apiVersion: v1
kind: ServiceAccount
metadata:
  name: auth-server
---
apiVersion: v1
kind: Service
metadata:
  name: oauth
  labels:
    app: auth-server
    service: auth-server
spec:
  ports:
  - name: http
    port: 80
    targetPort: 5000
  selector:
    app: auth-server
  type: LoadBalancer
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: auth-server
spec:
  replicas: 1
  selector:
    matchLabels:
      app: auth-server
      version: v1
  template:
    metadata:
      labels:
        app: auth-server
        version: v1
    spec:
      serviceAccountName: auth-server
      containers:
      - image: maho/oauth-server:0.2
        imagePullPolicy: IfNotPresent
        name: auth-server
        ports:
        - containerPort: 5000
