##
## テストマイクロサービス
##
---
## デプロイメント 
apiVersion: apps/v1
kind: Deployment
metadata:
  name: ms-counter
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ms-counter
  template:
    metadata:
      labels:
        app: ms-counter
    spec:
      containers:
      - name: ms-counter
        image: harbor.labo.local/tkr/ms-counter:__BUILDNUMBER__
        #image: maho/ms-counter:1.0
        imagePullPolicy: Always
        env:
          - name: REDIS_HOST
            valueFrom:
              configMapKeyRef:
                name: ms-counter-config
                key: redis_host
          - name: REDIS_PORT
            valueFrom:
              configMapKeyRef:	    
                name: ms-counter-config
                key: redis_port
---
## サービス
apiVersion: v1
kind: Service
metadata:
  name: ms-counter
spec:
  selector:
    app: ms-counter
  ports:
  - protocol: TCP
    port: 80
    targetPort: 3000
  type: LoadBalancer
