apiVersion: apps/v1
kind: Deployment
metadata:
  name: web-java-9
  labels:
    version: v1
spec:
  replicas: 1
  selector:
    matchLabels:
      app: webjava9
      version: v1      
  template:
    metadata:
      labels:
        app: webjava9
        version: v1
    spec:
      containers:
      - name: webjava
        image: harbor.labo.local/tkr/web-apl-openliberty:__BUILDNUMBER__        
        #image: maho/webapl-9:0.2
        ports:
        - containerPort: 9080
        imagePullPolicy: Always
        readinessProbe:
          httpGet:
            path: /health/ready
            port: 9080
          initialDelaySeconds: 30
          timeoutSeconds: 5
        livenessProbe:
          httpGet:
            path: /health/live
            port: 9080
          initialDelaySeconds: 30
          timeoutSeconds: 10
          failureThreshold: 3
---
apiVersion: v1
kind: Service
metadata:
  name: web-java-9
  labels:
    app: webjava9
spec:
  type: LoadBalancer  
  ports:
  - name: http    
    port: 80
    targetPort: 9080
    protocol: TCP    
  selector:
    app: webjava9

