apiVersion: apps/v1
kind: Deployment
metadata:
  name: takara-operator
spec:
  replicas: 1
  selector:
    matchLabels:
      name: takara-operator
  template:
    metadata:
      labels:
        name: takara-operator
    spec:
      serviceAccountName: takara-operator
      containers:
        - name: takara-operator
          # Replace this with the built image name
          image: docker.io/maho/takara-operator:v0.0.3
          command:
          - takara-operator
          imagePullPolicy: Always
          env:
            - name: WATCH_NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
            - name: POD_NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            - name: OPERATOR_NAME
              value: "takara-operator"
