apiVersion: v1
kind: ServiceAccount
metadata:
  name: web-login
---
apiVersion: v1
kind: Service
metadata:
  name: web-login
  labels:
    app: web-login
    service: web-login
spec:
  ports:
  - name: http
    port: 80
    targetPort: 5000
  selector:
    app: web-login
  type: LoadBalancer
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: web-login
spec:
  replicas: 1
  selector:
    matchLabels:
      app: web-login
      version: v1
  template:
    metadata:
      labels:
        app: web-login
        version: v1
    spec:
      serviceAccountName: web-login
      containers:
      - name: web-login
        image: maho/web-login:0.1
        imagePullPolicy: Always        
        ports:
        - containerPort: 5000
        env:
        - name: LDAP_URL
          value: "http://oauth-server:8000/login"
