apiVersion: v1
kind: Pod
metadata:
  name: nginx
spec:
  containers:
  - name: ubuntu
    image: ubuntu:18.04
    command: ["sh",  "-c", "sleep 3600; exit 0"]
    volumeMounts:    
    - mountPath: /etc/php.ini
      name: config

  volumes:
  - name: config
    configMap:
      name: php.ini

