apiVersion: v1
kind: Service
metadata:
  name: redis
  labels:
    db: redis
spec:
  ports:
  - port: 6379
    name: web
  clusterIP: None
  selector:
    db: redis
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: redis
spec:
  selector:
    matchLabels:
      db: redis
  serviceName: "redis"
  replicas: 1 
  template:
    metadata:
      labels:
        db: redis
    spec:
      terminationGracePeriodSeconds: 10
      containers:
      - name: redis
        image: redis:5.0.7
        ports:
        - containerPort: 6379
          name: redis-port
        volumeMounts:
        - name: data-vol
          mountPath: /data
  volumeClaimTemplates:
  - metadata:
      name: data-vol
    spec:
      accessModes: [ "ReadWriteOnce" ]
      storageClassName: "rook-ceph-block"
      resources:
        requests:
          storage: 5Gi
